[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[workspace.dependencies]
colored = "3.0.0"
