[package]
name = "host-rs"
version = "0.1.0"
edition = "2021"
authors = ["Biswajit Thakur"]
homepage = "https://github.com/BiswajitThakur/host-rs"
repository = "https://github.com/BiswajitThakur/host-rs"
readme = "README.md"
license = "MIT"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1

[dependencies]
regex = "1.10.2"
reqwest = "0.11.23"
futures = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }
dirs = "5.0.1"
csv = "1.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
ratatui = "0.26.0"
crossterm = "0.27.0"
