[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { workspace = true }
dirs = { workspace = true }
host-utils = { path = "../host-utils" }
anyhow = { workspace = true }
crossterm = { workspace = true }
