[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { workspace = true }
dirs = { workspace = true }
host = { path = "../host" }
storage = { path = "../storage"}
host-utils = { path = "../host-utils" }
