[package]
name = "host-rs"
version = "0.1.0"
edition.workspace = true

[dependencies]
# cli = { path = "../cli" }
host-utils = { path = "../host-utils" }
crossterm = { workspace = true }
dirs = { workspace = true }
clap = { workspace = true }
