[package]
name = "host-utils"
version = "0.1.0"
edition.workspace = true

[dependencies]
crossterm = { workspace = true }
dirs = { workspace = true }
indicatif = { workspace = true }
ureq = { workspace = true }
anyhow = { workspace = true }
